version: "3.9"
services:
  cluster:
    build:
      context: .
      dockerfile: cmd/Cluster/Dockerfile
      args:
        - PORT=${PORT}
    environment:
      - LISTEN_ADDR=:${PORT}
    expose:
      - ${PORT}
  requestcounter:
    depends_on:
      - cluster
    build:
      context: .
      dockerfile: cmd/RequestCounter/Dockerfile
      args:
        - PORT=${PORT}
    environment:
      - LISTEN_ADDR=:${PORT}
      - CLUSTER_ADDR=${CLUSTER_ADDR}
    deploy:
      replicas: 3
    expose:
      - ${PORT}
  nginx:
    image: nginx:latest
    environment:
      - PORT=${PORT}
      - REQCOUNTER_ADDR=${REQCOUNTER_ADDR}
    volumes:
      - ./cmd/nginx/nginx.conf:/nginx.conf.template:ro
      - ./cmd/nginx/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - requestcounter
    ports:
      - '${PORT}:${PORT}'
