version: "3.9"
services:
  cluster:
    build:
      context: .
      dockerfile: cmd/Cluster/Dockerfile
      args:
        - PORT=${PORT}
    environment:
      - LISTEN_ADDR=:${PORT}
    expose:
      - ${PORT}
  requestcounter:
    depends_on:
      - cluster
    build:
      context: .
      dockerfile: cmd/RequestCounter/Dockerfile
      args:
        - PORT=${PORT}
    environment:
      - LISTEN_ADDR=:${PORT}
      - CLUSTER_ADDR=${CLUSTER_ADDR}
    deploy:
      replicas: 3
    expose:
      - ${PORT}
  nginx:
    image: nginx:latest
    environment:
      - PORT=${PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - requestcounter
    ports:
      - '${PORT}:${PORT}'
